# Site settings
title: Tulip-HFT 
email: tuliphft@gmail.com 
url: tuliphft.com
#baseurl: /home/jasper/projects/jeckylexperiment/tuliphft 
description: "Tulip High Frequency Trading (Tulip-HFT) is a Registered Dutch company that sells Algorithmic Trading software designed for the cryptocurrency market."

# Color settings (hex-codes without the leading
# 
color: 
  primary: EC8B19 #80B3FF 
  secondary: 0D0D0B #FD6E8A
  secondary-dark: 0D0D0B #A2122F 
#Footer settings 
footer: 
  copyright: Tulip-HFT
  location: Netherlands 
  social: '@TulipHFT'
  credits: Credits
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

social:
  - title: twitter
    url: http://twitter.com/TulipHFT 
  - title: bitcoin
    url: https://bitcointalk.org/index.php?topic=941490  

# Postal address (add as many lines as necessary) 
        #address: 
        # - line: 3481 Melrose Place 
        # - line: Beverly Hills, CA 90210 

# Credits content
credits: 'This site is build with Freelancer, a free to use, open  source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
# Build settings 
markdown: kramdown 
permalink: pretty
